ECHO OFF
SET FILE=consensusPBFT.exe
SET PATH=D:\BlockChain\GoBlockChain\src\consensusPBFT\
SET TEMP1=%PATH%test\1111\%FILE%
SET TEMP2=%PATH%test\1112\%FILE%
SET TEMP3=%PATH%test\1113\%FILE%
SET TEMP4=%PATH%test\1114\%FILE%

ECHO ON
DEL %TEMP1%
DEL %TEMP2%
DEL %TEMP3%
DEL %TEMP4%
COPY %PATH%%FILE%   %TEMP1%
COPY %PATH%%FILE%   %TEMP2%
COPY %PATH%%FILE%   %TEMP3%
COPY %PATH%%FILE%   %TEMP4%

PAUSE